# Uncomment the next line to define a global platform for your project
 platform :ios, '13.0'

target 'PokeApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for PokeApp
  pod 'Moya'
  pod 'Kingfisher'
  pod 'SnapKit'

  target 'PokeAppTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'Nimble'
  end

  target 'PokeAppUITests' do
    # Pods for testing
  end

end
